name: MoneyPrintTurbo workflow actions
run-name: ${{ github.actor }} is CI/CD for MoneyPrintTurbo Actions ðŸš€
on:
  push:
    branches:
      - main
    tags: 
      - v*
  pull_request:
    branches:
      - main
    tags: 
      - v* 
  workflow_dispatch:
      inputs:
        environment:
          description: 'Select Environment'
          type: environment
          required: true
          options: 
          - prod
          - dev
          
jobs:
  Dev:
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'dev' and startsWith(github.event.ref, 'refs/tags')
    
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ðŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ðŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - run: echo dev.toml | base64 --decode > config.toml
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "start to setup Docker build"
      - run: echo "TAG_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV   
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to ACR
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push image
        run: |
          echo "push version ${{env.TAG_VERSION}}"
          docker build -t registry.cn-beijing.aliyuncs.com/chana/moneyprinterturbo:${{env.TAG_VERSION}} .
          docker push registry.cn-beijing.aliyuncs.com/chana/moneyprinterturbo:${{env.TAG_VERSION}}


      - run: echo "ðŸ This job's status is ${{ job.status }}."

  Prod: 
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: Dev
    if: github.event.inputs.environment == 'prod' and startsWith(github.event.ref, 'refs/tags')
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "start to setup Docker build"
      - run: echo "TAG_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV   
      - run: echo prod.toml | base64 --decode > config.toml
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ACR
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push image
        run: |
          echo "push version ${{env.TAG_VERSION}}"
          docker build -t registry.cn-beijing.aliyuncs.com/chana/moneyprinterturbo:${{env.TAG_VERSION}} .
          docker push registry.cn-beijing.aliyuncs.com/chana/moneyprinterturbo:${{env.TAG_VERSION}}
